### ISSUE TITLE
Why the name change?

### ISSUE THREAD

**Issue by jacquev6** [sqids/sqids-ocaml#1]
Hello @4kimov!

What's your motivation to change the name of hashids? (It may be worth explaining it on hashids.org and/or squids.org, not just in this issue).

My last commit on [hashids-ocaml](https://github.com/jacquev6/hashids-ocaml) was 5 years ago. OCaml has evolved since then, and I've *not* been following the changes. Adapting hashids-ocaml into sqids-ocaml, and supporting newer OCaml version will be a project for when I have more free time and motivation; I'll keep it in the back of my head though.

**Comment by 4kimov** [comment]
Hey @jacquev6,

Thanks for pinging! We're trying to upgrade Hashids with a few improvements, a bit more info here: https://github.com/orgs/hashids/discussions/92

Hashids website will be updated with redirects & explanations once we have some momentum on the new libraries.

Thank you for letting me know about OCaml. I don't expect you (or anyone else) to jump on implementing any of this, I just added you so that you have access to the repo -- I didn't want you to be excluded.

We are also trying something new this time - which is individual implementations under one Github org, so that we can have multiple maintainers - in case someone is not available for a specific language.

**Comment by jacquev6** [comment]
Thanks for the pointer, that's exactly what I was looking for and there are some pretty good points for evolving hashids.

**Comment by 4kimov** [comment]
Hey @jacquev6, just wanted to check-in and see if you've had a bit of time/motivation to take a stab at this one? The stars are slowly growing so there's demand. From my experience, LLMs can do a good bit of heavy lifting (since this is mostly a single file lib).

**Comment by jacquev6** [comment]
Hi @4kimov, no I'm afraid OCaml is still quite low on my priorities at the moment, and so is sqids-ocaml.
